version: 2

jobs:
  build:
    docker:
      - image: gengjiawen/v8-build:android
    working_directory: ~/v8-android-buildscripts
    steps:

      - checkout

      - run:
          name: Export settings from npm package
          command: |
            npm run export_npm_env

      - run:
          name: Patch V8
          command: |
            scripts/patch.sh android

      - run:
          name: Build V8
          command: |
            scripts/build.sh android
            scripts/archive.sh android

      - run:
          name: Build V8 No Intl
          command: |
            NO_INTL=1 scripts/build.sh android
            NO_INTL=1 scripts/archive.sh android

      - run:
          name: Archive
          command: |
            tar cvfz dist.tgz dist

      - store_artifacts:
          path: dist.tgz

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
